name: Autograding Tests
"on":
  - push
  - workflow_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    env:
      # For recording and parallelization to work you must set your CYPRESS_RECORD_KEY
      # in GitHub repo → Settings → Secrets → Actions
      COURSE: full-stack-development-comp3036-2025
      CI: true
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install PNPM 📦
        uses: pnpm/action-setup@v4
        with:
          version: 10.4.1
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - name: Install dependencies 🧪
        run: pnpm install

      ####################
      # Playwright
      ####################
      - name: Exercise - Pages
        id: npm1
        uses: WesternSydneyUniversity/autograding-command-grader@v3
        continue-on-error: true
        with:
          working-directory: .
          test-name: Exercise
          courseId: ${{env.COURSE}}
          sectionId: rest-apis-next-js-in-apis
          command: pnpm test
          timeout: 10
          max-score: 1

      - name: Autograding Reporter
        uses: education/autograding-grading-reporter@v1
        env:
          NPM1_RESULTS: "${{steps.npm1.outputs.result}}"
        with:
          runners: npm1
